name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.3'

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Build
      run: |
        go build -o main .

    - name: Run tests
      run: |
        go test -v ./...
        
    - name: Build Docker image
      run: docker build -t ipchecker:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ipchecker:latest
          docker stop ipchecker || true
          docker rm ipchecker || true
          docker run -d -p 8080:8080 --name ipchecker ${{ secrets.DOCKER_USERNAME }}/ipchecker:latest
